---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 'Core Function CloudfrontCreateInvalidation'

Metadata: {}

Parameters: {}

Mappings: {}

Conditions: {}

Resources:
    Function:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: cloudfront_create_invalidation/
            Handler: app.lambda_handler
            Runtime: python3.7
            Timeout: 3
            Environment: {}
            Events: {}
            Policies:
              - CodePipelineLambdaExecutionPolicy: {}
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - 'cloudfront:CreateInvalidation'
                    Resource:
                      - '*'

    Policy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            Description: 'CloudFront create invalidation invoke Policy'
            Path: /
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - 'lambda:InvokeFunction'
                    Resource:
                      - !GetAtt Function.Arn

    ParameterArn:
        Type: AWS::SSM::Parameter
        Properties:
            Description: 'CloudFront create invalidation function Arn'
            Type: String
            Name: '/core/functions/cloudfront-create-invalidation/arn'
            Value: !GetAtt Function.Arn

    ParameterName:
        Type: AWS::SSM::Parameter
        Properties:
            Description: 'CloudFront create invalidation function Name'
            Type: String
            Name: '/core/functions/cloudfront-create-invalidation/name'
            Value: !Ref Function

    ParameterPolicy:
        Type: AWS::SSM::Parameter
        Properties:
            Description: 'Function Invoke Policy Arn'
            Type: String
            Name: '/core/funcitons/cloudfront-create-invalidation/managed-policy'
            Value: !Ref Policy

Outputs:
    Function:
        Description: Cloudfront Cretate Invalidation Function
        Value: !Ref Function
    Arn:
        Description: SSM Parameter for Function
        Value: !Ref ParameterArn
    Name:
        Description: SSM Parameter for Function
        Value: !Ref ParameterName
    Policy:
        Description: SSM Parameter for Function
        Value: !Ref ParameterPolicy
