---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 'Core Functions Resources'

Metadata: {}

Parameters: {}

Mappings: {}

Conditions: {}

Resources:
    CloudfrontCreateInvalidation:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: './cloudfront_create_invalidation.yaml'
            Parameters: {}
            TimeoutInMinutes: 15

Outputs: {}
